version: "3.9"
services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.backend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   environment:
  #     DATABASE_HOST: "${DATABASE_HOST}"
  #     DATABASE_PORT: "${DATABASE_PORT}"
  #     DATABASE_USER: "${DATABASE_USER}"
  #     DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
  #     DATABASE_NAME: "{DATABASE_NAME}"
  #   networks:
  #     - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  # db:
  #   image: postgres:15
  #   container_name: postgres_db
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: app_db
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

volumes:
  db_data:

networks:
  app-network:
